language: python
python:
- '2.7'
- '3.6'
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - "/^feature\\/issue-\\d+(-\\S*)?$/"
  - "/^release\\/\\d+\\.\\d+(\\.\\d+)?$/"
stages:
- linting
- test
- name: deploy
  if: type != pull_request && branch = "master"
jobs:
  include:
  - stage: linting
    python: '3.6'
    script:
    - flake8 --select=E121,E123,E126,E226,E24,E704,W503,W504 --ignore=E501 app.py
      tests
  - stage: build_pages
    language: java
    jdk: oraclejdk8
    before_install:
    - chmod +x gradlew
    - chmod +x scripts/fetchpages.sh
    - chmod +x scripts/stagepages.sh
    script:
    - "./scripts/fetchpages.sh"
    - "./gradlew installSwagger buildSwagger asciidoctor"
    - "./scripts/stagepages.sh"
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      on:
        all_branches: true
  - stage: deploy
    python: '3.6'
    script: ignore
    before_install: ignore
    deploy:
    - provider: pypi
      on:
        tags: true
        branch: master
        python: '3.6'
        repo: ga4gh/data-repository-service-schemas
      user: ga4gh-cloud-workstream
      password:
        secure: O3xHQwUG2pEhU0FXmeaWzDY70iRz0J+LeXGhyH9UJz84WCSSfmwEyxH4gJlucHLEmUBV+nuwxbe6vRzN2jiO34qSXrdSV7fippw2ZCuYM+hwOz0rB42B0fUVqMBIMjAusKdoumaeOS15spOV+06qSAtzB+bhI0ZqhSEFy7yeX1qIdx33bJUSqB73r9be+gndafXG9vK2lqz0C8tMA3cYFze6alX3vde8dWYuTeq65XhXyqrwELhCMTVTYQmHit9Y7qMqcJdb5a/O/Q8QcmhxiowxfZXqzXtRKfAFaukq1FobG05WYVcz3Uwsog6EVkqlQ9WZ7LNv2ZskLRut+o/bq2zuYGoiEtjLu4SVaPQrgRrcAf4HisMx6elJIjQffNjaaZTJ89kMJq8lGV/t+HfBSEUwxU6gK3ueDIAHDLbnaPbGTPs8bBNo2XZ+7rRU3xCkiDB/ZwOktuwguGFBSOA7UT129JOp8yQ3y4G2SvwwMNo7KUKr2R4PDY5q6FG2XoZZqJHOkPP/iOvy3e+3gpUg3tGYxsQF2XJaarvzqOfkrHMMnlKmCrkcueVeIRyxbMfp/FylxAL4D4AY6xdM2Otl7+hZjB49ZruoRitoa+N5w6AEG0CaIQoJWQ3k2UIGektjdhrDszJS47Q65efjiO93XEcUiEXh2bM4KJfYDxHI13M=
before_install:
- python setup.py sdist
- pip install dist/ga4gh_drs_schemas-*.tar.gz
- npm install -g swagger2openapi
script:
- make schemas
- nosetests python/
- ga4gh_drs_client
